version: "3"
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ./db:/data/db
      - ./configdb:/data/configdb

  python:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    depends_on:
      - mongo
    environment:
      MONGO_ADDRESS: mongo
    env_file:
      - .env
