version: "3"
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017

  python:
    build:
      context: ..
      dockerfile: Dockerfile
    restart: always
    command: /bin/bash
    depends_on:
      - mongo
    tty: true
    volumes:
      - "..:/workspace"
    environment:
      MONGO_ADDRESS: mongo
